# Generated by Django 4.2.13 on 2024-06-07 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, verbose_name='Article namer')),
                ('description', models.CharField(max_length=255, verbose_name='Article description')),
                ('location', models.CharField(max_length=100, verbose_name='Article location')),
                ('reserved', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('notification_winner', models.BooleanField(default=True)),
                ('notification_no_bid', models.BooleanField(default=True)),
                ('publish', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
