# Generated by Django 4.2.13 on 2024-06-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.CharField(max_length=100, verbose_name='Article name'),
        ),
    ]
