# Generated by Django 4.2.13 on 2024-06-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
