# Generated by Django 4.2.13 on 2024-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='color',
            table='Color',
        ),
    ]
