# Generated by Django 4.2.13 on 2024-06-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_initial'),
        ('articles', '0008_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
