# Generated by Django 4.2.13 on 2024-06-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_subcategory'),
        ('articles', '0009_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(default=1, max_length=25, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory'),
            preserve_default=False,
        ),
    ]
