# Generated by Django 4.2.13 on 2024-06-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AlterModelTable(
            name='imageupload',
            table='ImageUpload',
        ),
    ]
