# Generated by Django 4.2.13 on 2024-06-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_delete_color_alter_imageupload_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('created',)},
        ),
    ]
