# Generated by Django 4.2.13 on 2024-06-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='dislike',
            new_name='bad',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='good',
        ),
    ]
