# Generated by Django 4.2.13 on 2024-06-19 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0014_rename_dislike_like_bad_rename_like_like_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='article',
        ),
        migrations.AlterField(
            model_name='like',
            name='bad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='good',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='article',
            field=models.ManyToManyField(to='articles.article'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
