# Generated by Django 4.2.13 on 2024-06-21 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_article_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
