# Generated by Django 4.2.13 on 2024-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_amount',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
