# Generated by Django 4.2.13 on 2024-06-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_unsubscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
