# Generated by Django 5.0 on 2024-10-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidsWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bids', models.PositiveIntegerField(default=1)),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BidsWinner',
            },
        ),
        migrations.CreateModel(
            name='BidsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bids', models.PositiveIntegerField(default=1)),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
            options={
                'db_table': 'BidsHistory',
            },
        ),
    ]
