# Generated by Django 4.2.13 on 2024-06-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0009_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetBidArticle',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.article')),
                ('set_bid', models.CharField(blank=True, choices=[('1', 'Bidder increment'), ('2', 'Auto increment')], max_length=1, null=True)),
                ('bid_amount', models.IntegerField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_update', models.BooleanField()),
                ('choose_date_time', models.BooleanField()),
                ('total_images', models.IntegerField()),
                ('verify_email_register', models.BooleanField()),
                ('theme', models.CharField(choices=[('L', 'Light'), ('D', 'Dark')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
