# Generated by Django 4.2.13 on 2024-06-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setbidarticle',
            name='set_bid',
            field=models.CharField(blank=True, choices=[('1', 'Bidder increment'), ('2', 'Auto increment')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
