# Generated by Django 5.0 on 2024-10-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminauction', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetBidArticle',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.article')),
                ('set_bid', models.CharField(blank=True, choices=[('1', 'Bidder increment'), ('2', 'Auto increment')], max_length=1)),
                ('bid_amount', models.IntegerField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_update', models.BooleanField()),
                ('choose_date_time', models.BooleanField()),
                ('total_images', models.IntegerField()),
                ('theme', models.CharField(choices=[('L', 'Light'), ('D', 'Dark')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('site_name', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=35)),
            ],
        ),
    ]
