# Generated by Django 4.2.13 on 2024-07-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauction', '0002_alter_setbidarticle_set_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='site_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
