# Generated by Django 4.2.13 on 2024-07-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauction', '0003_userpermission_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='site_name',
            field=models.CharField(max_length=20),
        ),
    ]
