# Generated by Django 4.2.13 on 2024-07-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminauction', '0004_alter_userpermission_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='verify_email_register',
        ),
    ]
