# Generated by Django 4.2.13 on 2024-09-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauction', '0005_remove_userpermission_verify_email_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='domain',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
