# Generated by Django 4.2.13 on 2024-09-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauction', '0006_userpermission_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feearticle',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
