# Generated by Django 4.2.13 on 2024-09-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauction', '0007_alter_feearticle_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feearticle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
