# Generated by Django 5.0.9 on 2024-09-16 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauction', '0008_alter_feearticle_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feearticle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feearticle',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='setbidarticle',
            name='bid_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
