# Generated by Django 5.0.9 on 2024-09-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauction', '0009_alter_feearticle_created_alter_feearticle_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setbidarticle',
            name='bid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
