# Generated by Django 4.2.13 on 2024-06-08 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100)),
                ('bid', models.PositiveIntegerField()),
                ('bid_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('email', models.EmailField(max_length=254)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('slug', models.SlugField(unique=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
