# Generated by Django 4.2.13 on 2024-06-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdone',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
