# Generated by Django 4.2.13 on 2024-09-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winner', '0002_alter_checkoutdone_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdone',
            name='bid_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
